# Salary Dataset
applying simple linear regression on salary dataset from scratch

In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv("Salary_dataset.csv")

In [3]:
df.head()

Unnamed: 0  YearsExperience   Salary
0           0              1.2  39344.0
1           1              1.4  46206.0
2           2              1.6  37732.0
3           3              2.1  43526.0
4           4              2.3  39892.0

In [11]:
X, y = df['YearsExperience'].values, df['Salary'].values
type(X)
type(y)

# X=feature and y=target
# both are taken as ndarray

numpy.ndarray

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2, random_state=2)

In [21]:
X_train.size

24

In [18]:
X_train_mean = np.mean(X_train)
X_train_mean

5.754166666666666

In [17]:
y_train_mean = np.mean(y_train)
y_train_mean

78502.20833333333

In [45]:
class simple_lr:

    def __init__(self, X_train_mean, y_train_mean, X_train, y_train):
        self.m = self.find_m(X_train_mean, y_train_mean, X_train, y_train)
        self.b = self.find_b(X_train_mean, y_train_mean)

        print(self.m)
        print(self.b)

    def find_m(self, X_train_mean, y_train_mean, X_train, y_train):        
        num=0
        deno=0
        for i in range(X_train.size):
            num = num + ((X_train[i]-X_train_mean)*(y_train[i]-y_train_mean))
            deno = deno + ((X_train[i]-X_train_mean)*(X_train[i]-X_train_mean))
        
        return num/deno

    def find_b(self, X_train_mean, y_train_mean):
        return (y_train_mean - self.m*X_train_mean)
    
    def predit_lr(self, X_test,m,b):
        return m*X_test+b


In [24]:
X_test

array([1.4, 1.2, 4.6, 3.8, 7.2, 6.1])

In [25]:
y_test

array([46206., 39344., 61112., 57190., 98274., 93941.])

In [46]:
slr_obj = simple_lr(X_train_mean, y_train_mean, X_train, y_train)

9569.586885432866
23437.21046340505


In [51]:
m=slr_obj.find_m(X_train_mean, y_train_mean, X_train, y_train)
b=slr_obj.find_b(X_train_mean, y_train_mean)
y_pred = slr_obj.predit_lr(X_test,m,b)

In [52]:
y_pred

array([36834.63210301, 34920.71472592, 67457.3101364 , 59801.64062805,
       92338.23603852, 81811.69046455])